# Generated by Django 5.0.6 on 2024-06-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
