# Generated by Django 5.0.6 on 2024-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_frist_name_usuario_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
