# Generated by Django 5.0.6 on 2024-06-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
